currs:
  EUR_USD:
    pip_size: 0.0001
    pip_gap: 0.5

  USD_JPY:
    pip_size: 0.01
    pip_gap: 0.5

  AUD_USD:
    pip_size: 0.0001
    pip_gap: 0.5

  AUD_JPY:
    pip_size: 0.01
    pip_gap: 1.5