50:
  half_min_trans_num: 0
  max_loss: -0.0001

55:
  half_min_trans_num: 0
  max_loss: -0.0002

60:
  half_min_trans_num: 0
  max_loss: -0.0003

65:
  half_min_trans_num: 0
  max_loss: -0.0004
  
70:
  half_min_trans_num: 0
  max_loss: -0.0005

75:
  half_min_trans_num: 0
  max_loss: -0.0006

80:
  half_min_trans_num: 0
  max_loss: -0.0007

85:
  half_min_trans_num: 0
  max_loss: -0.0008

90:
  half_min_trans_num: 0
  max_loss: -0.0009