currency:
  instrument: "EUR_USD"
  pip: 0.0001

wma:
  lists_size: 300
  long_moving_window: 200
  short_moving_window: 20

order:  
  units: 1
  stop_loss_limit: 3
  profit_target: 0.25 
  price_allowed_buffer: 0.1 

loss_skip:
  max_skips: 1
  consecutive_losses: 2