curr: 
  instrument: "EUR_USD"

pip_size:
  EUR_USD: 0.0001
  USD_JPY: 0.01
  AUD_USD: 0.0001
  EUR_GBP: 0.0001  


wma:
  lists_size: 300
  long_moving_window: 1000
  short_moving_window: 10
  slope_num: 20
  min_order_angle: 25


order:  
  units: 1
  stop_loss_limit: 2
  order_num_limit: 10
  profit_target: 0.2
  price_allowed_buffer: 0.2 

loss_skip:
  max_skips: 1
  consecutive_losses: 2

