currency:
  instrument: "EUR_USD"
  pip: 0.0001

wma:
  lists_size: 300
  long_moving_window: 1000
  short_moving_window: 50

order:  
  units: 1
  stop_loss_limit: 3
  order_num_limit: 10
  profit_target: 0.1
  price_allowed_buffer: 0.2 

loss_skip:
  max_skips: 1
  consecutive_losses: 2