tick_speed:
  iter_num: 300


direction:
  target_num: 3
  min_count: 2
  min_count_mulitplier: 1
  dir_min_trans_multiplier_long: 2
  dir_min_trans_multiplier_short: 1  
  dir_recalc_multiplier: 5


profit:
  profit_target_num: 1
  price_allowed_buffer: 0.5 
  loss_limit_num: 25


order_run:  
  run_min_trans_multiplier: 25
  

execution:  
  instrument: 'EUR_USD'
  num_of_bets: 10